# Generated by Django 4.0.4 on 2022-04-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
                ('joylashuv', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('sana', models.DateTimeField()),
                ('brend', models.CharField(blank=True, max_length=30)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('kelgan_narx', models.IntegerField()),
                ('sotuv_narx', models.IntegerField(blank=True)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
                ('manzil', models.CharField(max_length=30)),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ombor')),
            ],
        ),
    ]
